import { gql, useQuery } from "@apollo/client";
import { BigNumber, Contract, ethers } from "ethers";
import NFT_MARKET from '../NFTMarket.json'
import Head from 'next/head'
 import HomePage from '../pages/Home/HomePage'
import LoadingScreen from "./Loader/LoadingScreen";
 
export default function Home() {

  return (
    <>
      <Head>
        <title>Nft</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <div>
     <HomePage/>
     {/* <LoadingScreen/> */}
      </div>
    </>
  )
}
